#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pydot_ng
Version  : 1.0.0
Release  : 2
URL      : https://pypi.python.org/packages/de/64/86b0502c3644190c0b9fed0e378ee18f31b1f0262bdead1eb9ac1d404529/pydot_ng-1.0.0.tar.gz
Source0  : https://pypi.python.org/packages/de/64/86b0502c3644190c0b9fed0e378ee18f31b1f0262bdead1eb9ac1d404529/pydot_ng-1.0.0.tar.gz
Summary  : Python interface to Graphviz's Dot
Group    : Development/Tools
License  : MIT
Requires: pydot_ng-python
Requires: graphviz
Requires: pyparsing
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyparsing
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
pydot - Python interface to Graphviz's Dot language
---------------------------------------------------
Ero Carrera (c) 2004-2007

%package python
Summary: python components for the pydot_ng package.
Group: Default

%description python
python components for the pydot_ng package.


%prep
%setup -q -n pydot_ng-1.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490031257
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1490031257
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
